### ISSUE TITLE
winit + mozangle?

### ISSUE THREAD

**Issue by ashikuri** [servo/mozangle#42]
hello, I would like to know how we could winit + mozangle or glutin + mozangle

**Comment by jdm** [comment]
This is possible by following what Servo's window builds used to do when we relied on glutin.
* https://github.com/servo/servo/blob/9dbc6554f087ca3675104fb1bac45b0c442a0158/ports/glutin/app.rs#L241-L250
* https://github.com/servo/servo/blob/9dbc6554f087ca3675104fb1bac45b0c442a0158/ports/glutin/headed_window.rs#L120-L132
* https://github.com/servo/servo/blob/9dbc6554f087ca3675104fb1bac45b0c442a0158/components/servo/Cargo.toml#L94-L95
And then we made sure that libEGL.dll and libGLESv2.dll we copied from the mozangle build directory to the final target directory next to the executable: https://github.com/servo/servo/blob/9dbc6554f087ca3675104fb1bac45b0c442a0158/python/servo/build_commands.py#L718-L722

**Comment by ashikuri** [comment]
ok thanks ^^
