### ISSUE TITLE
Heads-up: UB due to misuse of mem::zeroed will soon lead to panic 

### ISSUE THREAD

**Issue by RalfJung** [servo/mozangle#43]
[Here](https://github.com/servo/mozangle/blob/9539b4490316fe56223924cae6e4862b8260c16d/src/shaders/mod.rs#L137), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it creates a  `ShBuiltInResources` with `mem::zeroed()`. In the near future the call to `mem::zeroed()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/71274), and our crater run determined that this crate will be affected.

The reason that type cannot be zero-initialized is that 0 is not a valid value for [`ShArrayIndexClampingStrategy`](https://github.com/servo/mozangle/blob/88d2c0df0cc3a57968405225e27887bce3bc04a9/src/shaders/bindings.rs#L94), which is the type of one of the fields of `ShBuiltInResources`.

**Comment by staktrace** [comment]
With rust 1.48 this error is now happening, blocking the servo/webrender repo from getting updates from mozilla-central. See https://github.com/servo/webrender/pull/4168#issuecomment-731373901
