### ISSUE TITLE
Can not update Angle

### ISSUE THREAD

**Issue by kaiwk** [servo/mozangle#51]
I can not update gfx/angle as the README said in section `Updating Angle`. Execute `python3 generate_build_data.py` gives error following:

> Traceback (most recent call last):
  File "/Users/kai/projects/mozangle/generate_build_data.py", line 104, in <module>
    run()
  File "/Users/kai/projects/mozangle/generate_build_data.py", line 20, in run
    parse_lib(ANGLE, data[lib], ".common")
  File "/Users/kai/projects/mozangle/generate_build_data.py", line 43, in parse_lib
    exec(code, env, env)
  File "/Users/kai/projects/mozangle/gfx/angle/moz.build.common", line 3, in <module>
    if CONFIG['CC_TYPE'] in ('clang', 'clang-cl'):
KeyError: 'CC_TYPE'

**Comment by jdm** [comment]
Looks like you need to update https://github.com/servo/mozangle/blob/b261771a0eb5cd298451597ee4faa5747ac9e511/generate_build_data.py#L34 to include CC_TYPE=clang

**Comment by kaiwk** [comment]
I have tried fix the `generate_build_data.py` (probably messed up, because i don't know what i am really doing...), finally I found that the newest `gfx/angle` have a directory called `libANGLE`, and the build script will include a file from that directory. Just think the README may need a update

**Comment by sagudev** [comment]
https://github.com/servo/mozangle/pull/69 landed with new version of angle.
